Ingestion refactor and tweaks
c3g/chord_metadata_service pull request #353
Opened 2022-11-05 16:39 UTC by davidlougheed

2022-12-15 22:20 UTC, brouillette approved these changes
Works locally!
Able to update an `extra_properties` field for a an `individual` by simply reingesting the newly modified phenopackets file

2022-12-15 22:45 UTC, brouillette requested changes, later dismissed
Nitpicking, but looks good otherwise

2022-12-15 22:45 UTC, brouillette commented on .github/workflows/build.yml
> +        uses: bento-platform/bento_build_action@v0.6
might we want to update `bento-platform/bento_build_action` to `v0.9.3`?

2022-12-16 00:42 UTC, davidlougheed commented
i also fixed the image build so that it would work for the `develop` branch...

2022-12-16 18:58 UTC, brouillette requested changes
getting this error now
```
  File "/app/chord_metadata_service/restapi/dats_schemas.py", line 47, in _get_creators_schema
    dats_creators_schema = open(os.path.join(DATS_PATH, '{}.json'.format(creator_type)))
FileNotFoundError: [Errno 2] No such file or directory: '/app/chord_metadata_service/dats/person_schema.json'
```

2022-12-16 19:32 UTC, brouillette approved these changes
works for me!

2022-12-16 19:33 UTC, merged