Codecov github actions
c3g/chord_metadata_service pull request #393
Opened 2023-04-17 16:41 UTC by v-rocheleau

Codecov's pypi package was [deprecated](https://about.codecov.io/blog/message-regarding-the-pypi-package/#:~:text=On%20April%2012%2C%202023%2C%20Codecov,used%20package%20from%20active%20support.&text=As%20this%20package%20was%20unmaintained,to%20be%20made%20functional%20again) last week.

This PR removes the dependency on the old codecov python package, and replaces it with a Github Action step.

2023-04-17 17:01 UTC, davidlougheed requested changes

2023-04-17 17:01 UTC, davidlougheed commented on pyproject.toml
> -codecov = "^2.1.12"
this needs a corresponding (should be automated by poetry) removal from the lockfile

2023-04-17 17:31 UTC, v-rocheleau commented on pyproject.toml
> -codecov = "^2.1.12"
Good catch, didn't know I had to run `poetry lock` for it to update

2023-04-17 20:11 UTC, davidlougheed approved these changes
lgtm

2023-04-18 12:58 UTC, davidlougheed commented on pyproject.toml
> -codecov = "^2.1.12"
there are commands that remove an entry from pyproject.toml and poetry.lock at once (see poetry docs), but if you remove an item by hand you need the lock command yeah

2023-04-18 15:23 UTC, merged