refact!: define a "scopeable model" base class + modelviewset scoping
c3g/chord_metadata_service pull request #536
Opened 2024-09-10 14:41 UTC by davidlougheed

2024-11-27 17:49 UTC, davidlougheed commented
@v-rocheleau this is still WIP, but I would like to know your thoughts on the general approach/abstractions chosen

2024-12-20 20:04 UTC, gsfk commented
is this not possible? 

`api/individuals?project=<id>`

2024-12-20 20:04 UTC, davidlougheed commented
should be - i'll double check...

2025-01-06 19:27 UTC, v-rocheleau commented on chord_metadata_service/authz/viewset.py
> +        # TODO: there must be a better way to enforce this without manual flagging
We could break this into two classes. One for unscoped authz, and another one that extends the first for scoped authz.

2025-01-06 21:36 UTC, v-rocheleau requested changes
First pass

2025-01-06 21:36 UTC, v-rocheleau commented on chord_metadata_service/chord/views_search.py
> +                [r async for r in queryset],
Why is this needed?

2025-01-06 21:36 UTC, v-rocheleau commented on chord_metadata_service/experiments/models.py
> +                "prefetch_related": ("experiemnt",),
Typo

2025-01-06 21:36 UTC, v-rocheleau commented on chord_metadata_service/authz/viewset.py
> +    pass
I would add a comment to indicate that this is the equivalent of a `viewsets.ModelViewSet` but with a custom `viewsets.GenericViewSet` implementation (`BentoAuthzModelGenericViewSet`).
I mistook it for a WIP piece of code before I looked into the changes in the views.

2025-01-06 21:36 UTC, v-rocheleau commented on chord_metadata_service/discovery/scopeable_model.py
Good idea!

2025-01-06 21:36 UTC, v-rocheleau commented on chord_metadata_service/experiments/models.py
>      linked to a specific bisample.
Not a change, but we may as well fix this `bisample` typo here.

2025-01-07 19:03 UTC, v-rocheleau requested changes

2025-01-07 19:03 UTC, v-rocheleau commented on chord_metadata_service/experiments/api_views.py
> +class ExperimentBatchViewSet(mixins.ListModelMixin, BentoAuthzModelGenericViewSet):
As it is now, all concrete views extending `BentoAuthzModelGenericViewSet` are also extending `mixins.ListModelMixin`.
If `BentoAuthzModelGenericViewSet` remains like that (an authz enabled replacement for BatchViewSet), I think it would be better to include the `mixins.ListModelMixin` in `BentoAuthzModelGenericViewSet`

2025-01-07 19:03 UTC, v-rocheleau commented on chord_metadata_service/phenopackets/api_views.py
> +    permission_classes = (BentoDeferToHandler,)
Missing `scope_enabled` ?
Also, I think we can avoid using `BentoDeferToHandler` as the permission class and factor out the authz logic to `BentoAuthzModelGenericViewSet`.
Maybe by breaking `BentoAuthzModelGenericViewSet` into two classes, including one for batch viewsets

2025-01-08 21:40 UTC, gsfk commented
Search working well, only trouble so far is from `api/overview` which seems to ignore scope.

2025-01-09 18:43 UTC, davidlougheed commented on chord_metadata_service/chord/views_search.py
> +                [r async for r in queryset],
refactored + added a comment - queryset becomes an async iterator in an async context, and groupby only takes normal sync iterators/iterables.

2025-01-15 18:41 UTC, v-rocheleau requested changes
Final requests I think, looks good!

2025-01-15 18:41 UTC, v-rocheleau commented on chord_metadata_service/authz/viewset.py
> +    </!!!>
We could enforce this by implementing a `get_queryset` here that raises a `NotImplementedError`.

2025-01-15 18:41 UTC, v-rocheleau commented on chord_metadata_service/experiments/api_views.py
> +            return P_QUERY_DATA
Would add a comment to specify that `create` maps to `P_QUERY_DATA` because `POST` requests are used to include body params for search.

2025-01-15 18:41 UTC, v-rocheleau commented on chord_metadata_service/patients/models.py
> +            "project": {
```python
"filter": "phenopackets__dataset__project_id",
"prefetch_related": ("phenopackets__dataset_set",)
```

2025-01-15 18:41 UTC, v-rocheleau commented on chord_metadata_service/phenopackets/api_views.py
> +        if self.action in ("list", "create"):
Would add a comment to explain why `create` maps to `P_QUERY_DATA`

2025-01-15 18:41 UTC, v-rocheleau commented on chord_metadata_service/restapi/api_views.py
> +        - project (optional), dataset (optional): scope for search overview
I think the permission_classes are missing for this endpoint.

2025-01-15 18:41 UTC, v-rocheleau commented on chord_metadata_service/resources/tests/test_api.py
> +    def test_list_resources_scope_dne(self):
Not sure I understand why these are expecting 403 responses with `one_authz_get`

2025-01-15 18:41 UTC, v-rocheleau commented on chord_metadata_service/authz/viewset.py
Would it be too complicated to have full test cov here?

2025-01-15 19:16 UTC, davidlougheed commented on chord_metadata_service/restapi/api_views.py
> +        - project (optional), dataset (optional): scope for search overview
the default is BentoDeferToHandler (defined in settings), but I'll make it explicit

2025-01-15 19:26 UTC, gsfk approved these changes
Working well for me so far.

2025-01-15 20:06 UTC, davidlougheed commented on chord_metadata_service/authz/viewset.py
was being lazy, done.

2025-01-15 20:11 UTC, v-rocheleau commented on chord_metadata_service/resources/tests/test_api.py
> +    def test_list_resources_scope_dne(self):
Explanation: 403 happens with an invalid scope because the permissions cannot be determined on an authz protected endpoint.
We can add a note in a comment for that.

2025-01-15 20:46 UTC, gsfk commented
post-approval comment: behaviour when mismatching projects & datasets is not always consistent. If I manage to request a project_id and and an incorrect dataset_id (from another project, say), I get a mix of behaviours: 

- `/api/public_rules` returns a sensible error message
- `/api/individuals` returns "Forbidden"

2025-01-15 20:51 UTC, v-rocheleau approved these changes
LGTM! Nice work

2025-01-15 20:51 UTC, v-rocheleau commented on chord_metadata_service/restapi/exception_handler.py
Nice!

2025-01-15 20:55 UTC, merged