chore!: remove unused top-level phenopackets endpoints
c3g/chord_metadata_service pull request #553
Opened 2024-11-27 17:30 UTC by davidlougheed

2024-12-06 15:23 UTC, davidlougheed commented
@gsfk could you verify i'm not removing anything you use here?

2024-12-06 20:16 UTC, gsfk approved these changes

2024-12-12 22:07 UTC, v-rocheleau requested changes
Small request, will take a closer look at interpretation changes first thing tomorrow.

2024-12-12 22:07 UTC, v-rocheleau commented on chord_metadata_service/patients/models.py
> -
These fields are still in the Individual schema and descriptions dict.

2024-12-13 00:20 UTC, davidlougheed commented on chord_metadata_service/patients/models.py
> -
good point

2024-12-13 17:00 UTC, v-rocheleau requested changes
Looks good, validated that the endpoints removed are not used elsewhere.
Few things:
- There is still the (now unused) `fhir_utils.py` file, which links to hl7 and FHIR mapping files.
- `restapi/schemas` has an unused `FHIR_BUNDLE_SCHEMA`
- `restapi/semantic_mappings/README.md` can probably be removed

2024-12-13 17:21 UTC, v-rocheleau reviewed
Lint fails, otherwise LGTM!

2024-12-13 17:55 UTC, merged